# Configuraci√≥n de usuario para mlops4ofp

mode: "developer"   # "developer" o "student"

# URL remota de DVC (DAGsHub, GDrive, S3, etc.)
dvc_remote_url: ""

# MLflow (por ejemplo DAGsHub)
mlflow_tracking_uri: ""

# Credenciales DAGsHub (opcionales)
dagshub_username: ""
dagshub_token: ""
